config/routes.rb
Rails.application.routes.draw do

  get 'admin' => 'admin#index'

  namespace :admin do
    resources :stores, :except => [:post, :delete]
    resources :leaks, :except => [:post, :delete]
    resources :contacts, :except => [:post, :delete]
  end

  # devise_for :users
  devise_for :users, skip: :all
  devise_scope :user do
    get 'login' => 'devise/sessions#new', as: :new_user_session
    post 'login' => 'devise/sessions#create', as: :user_session
    delete 'logout' => 'devise/sessions#destroy', as: :destroy_user_session
  end

  get 'stores/index'
  post 'stores/contact'
  post 'stores/leak'
  get '/stores/:id',to: 'stores#index'

  # resources :prefs, only: :show, param: :name
  get '/:name', to: 'prefs#show', param: :name
  root to: 'stores#index'

  namespace :api,{format: 'json'} do
    resources :stores, only: [:index,:show]
    resources :prefs, only: [:index, :show], param: :name
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
# frozen_string_literal: true

class City < ApplicationRecord
  belongs_to :pref
end

app/models/inquiry.rb
# frozen_string_literal: true

class Inquiry < ApplicationRecord
  validates :message, presence: true
end

app/models/leak.rb
# frozen_string_literal: true

class Leak < ApplicationRecord
  validates :name, presence: true
  validates :address, presence: true
  validates :url, presence: true
  validates :wifi, presence: true
  validates :socket, presence: true
  validates :smoking, presence: true
end

app/models/mainstore.rb
# frozen_string_literal: true

class Mainstore < ApplicationRecord
  has_many :stores, dependent: :destroy
  validates :name, presence: true

  mount_uploader :image, ImageUploader
end

app/models/pref.rb
# frozen_string_literal: true

class Pref < ApplicationRecord
  has_many :citys, dependent: :destroy
end

app/models/store.rb
# frozen_string_literal: true

class Store < ApplicationRecord
  belongs_to :mainstore
  belongs_to :pref

  validates :name, presence: true
  validates :prefecture, presence: true
  validates :city, presence: true
  validates :other_address, presence: true
  validates :access, presence: true
  validates :tel, presence: true
  validates :business_hour, presence: true
  validates :wifi, presence: true
  validates :socket, presence: true
  validates :name, presence: true
  validates :smoking, presence: true
  validates :lat, presence: true
  validates :lng, presence: true
  validates :is_open, presence: true
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
    :recoverable, :rememberable, :validatable
end

app/controllers/admin/contacts_controller.rb
# frozen_string_literal: true

module Admin
  class ContactsController < ApplicationController
    before_action :authenticate_user!

    # Storeに関して
    def index
      @contacts = Inquiry.page(params[:page]).per(25).order(id: :desc)
      @all_contacts = Inquiry.all
      respond_to do |format|
        format.html
        format.csv do
          send_data render_to_string, filename: 'contacts.csv', type: :csv
        end
      end
    end
  end
end

app/controllers/admin/leaks_controller.rb
# frozen_string_literal: true

module Admin
  class LeaksController < ApplicationController
    before_action :authenticate_user!

    # Storeに関して
    def index
      @leaks = Leak.page(params[:page]).per(25).order(id: :desc)
      @all_leaks = Leak.all
      respond_to do |format|
        format.html
        format.csv do
          send_data render_to_string, filename: 'leaks.csv', type: :csv
        end
      end
    end
  end
end

app/controllers/admin/stores_controller.rb
# frozen_string_literal: true

module Admin
  class StoresController < ApplicationController
    before_action :authenticate_user!

    # Storeに関して
    def index
      @stores = Store.page(params[:page]).per(25).includes(:mainstore)
      @mainstores = Mainstore.all
      @allstores = Store.all
      respond_to do |format|
        format.html
        format.csv do
          send_data render_to_string, filename: 'stores.csv', type: :csv
        end
      end
    end

    def show
      @store = Store.find(params[:id])
    end

    def edit
      @store = Store.find(params[:id])
    end

    def update
      @store = Store.find(params[:id])
      if @store.update(store_params)
        # updateが完了したら一覧ページへリダイレクト
        redirect_to admin_stores_path
      else
        # updateを失敗すると編集ページへ
        render 'edit'
      end
    end

    private

    def store_params
      params.require(:store).permit(:name, :prefecture, :city, :other_address,
        :tel, :business_hour, :chair, :hp, :wifi,
        :socket, :smoking, :iccard, :is_open, :lat, :lng)
    end
  end
end

app/controllers/admin_controller.rb
# frozen_string_literal: true

class AdminController < ApplicationController
  before_action :authenticate_user!

  def index
  end
end

app/controllers/api/prefs_controller.rb
# frozen_string_literal: true

class Api::PrefsController < ApplicationController
  def index
    @prefs = Pref.all
  end

  def show
    @pref = Pref.find_by(name: params[:name])
    @stores = Store.all.includes(:mainstore).where(is_open: true).where(pref_id: @pref.id)
  end
end

app/controllers/api/stores_controller.rb
# frozen_string_literal: true

class Api::StoresController < ApplicationController
  def index
    @stores = Store.all.includes(:mainstore).where(is_open: true)
    @mainstores = Mainstore.all
  end

  def show
    @store = Store.find(params[:id])
  end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private

  def after_sign_in_path_for(resource)
    admin_path # ログイン後に遷移するpathを設定
  end

  def after_sign_out_path_for(resource)
    root_path # ログアウト後に遷移するpathを設定
  end
end

app/controllers/prefs_controller.rb
# frozen_string_literal: true

class PrefsController < ApplicationController
  def show
    @pref = Pref.find_by(name: params[:name])
    @stores = Store.all.includes(:mainstore, :pref).where(is_open: true).where(pref: @pref)
    @mainstores = Mainstore.all
  end
end

app/controllers/stores_controller.rb
# frozen_string_literal: true

class StoresController < ApplicationController
  def index
    @stores = Store.all.includes(:mainstore)
    @mainstores = Mainstore.all
  end

  def contact
    message = params[:inquiry][:message]
    email = params[:inquiry][:email]
    inquiry = Inquiry.new(email: email, message: message)
    if inquiry.save
      InquiryMailer.send_mail(inquiry).deliver_now
    else
      render action: 'index'
    end
  end

  def leak
    name = params[:leak][:name]
    address = params[:leak][:address]
    url = params[:leak][:url]
    socket = params[:leak][:socket]
    wifi = params[:leak][:wifi]
    smoking = params[:leak][:smoking]
    leak = Leak.new(name: name,
                    address: address,
                    url: url,
                    socket: socket,
                    wifi: wifi,
                    smoking: smoking)
    if leak.save
      LeakMailer.send_mail(leak).deliver_now
    else
      render action: 'index'
    end
  end

  def csv_export
    File.open('allStores.csv', 'w') do |f|
      csv_string = CSV.generate do |csv|
        csv << Store.column_names
        stores = Store.where(id: [1..4658])
        stores.each do |store|
          csv << store.attributes.values_at(*Store.column_names)
        end
      end
      f.puts csv_string
    end
  end

  private

  def inquiry_params
    params.require(:leak).permit(:email, :message)
  end
end

app/helpers/admin_helper.rb
# frozen_string_literal: true

module AdminHelper
end

app/helpers/api/stores_helper.rb
# frozen_string_literal: true

module Api::StoresHelper
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/stores_helper.rb
# frozen_string_literal: true

module StoresHelper
end

app/views/admin/contacts/index.html.erb
<h1 class="admin_title">Admin Contact</h1>

<ul>
	<li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
	<li><%= link_to 'csv出力', admin_contacts_path(format: :csv) %></li>
</ul>

<table class="highlight centered responsive-table">
	<thead>
		<tr>
		<th>ID</th>
			<th>Message</th>
			<th>Email</th>
			<th>送信時間</th>
		</tr>
	</thead>
	<tbody>
	<% @contacts.each do |contact| %>
		<tr>
			<td><%= contact.id %></td>
			<td><%= contact.message %></td>
			<td><%= contact.email %></td>
			<td><%= contact.created_at.strftime("%Y/%m/%d %H:%M:%S") %></td>
		</tr>
	<% end %>
	</tbody>
</table>
<%= paginate @contacts %>

app/views/admin/leaks/index.html.erb
<h1 class="admin_title">Admin Leak</h1>

<ul>
	<li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
	<li><%= link_to 'csv出力', admin_leaks_path(format: :csv) %></li>
</ul>

<table class="highlight centered responsive-table">
	<thead>
		<tr>
			<th>ID</th>
			<th>店名</th>
			<th>住所</th>
			<th>URL</th>
			<th>電源</th>
			<th>Wi-Fi</th>
			<th>喫煙</th>
			<th>送信時間</th>
		</tr>
	</thead>
	<tbody>
	<% @leaks.each do |leak| %>
		<tr>
			<td><%= leak.id %></td>
			<td><%= leak.name %></td>
			<td><%= leak.address %></td>
			<td><%= leak.url %></td>
			<td><%= leak.socket %></td>
			<td><%= leak.wifi %></td>
			<td><%= leak.smoking %></td>
			<td><%= leak.created_at.strftime("%Y/%m/%d %H:%M:%S") %></td>
		</tr>
	<% end %>
	</tbody>
</table>
<%= paginate @leaks %>

app/views/admin/stores/edit.html.erb
<h1 class="admin_title"><%= @store.name %>@Admin</h1>
<%= form_for(@store, :url => {:action => 'update'} ) do |f| %>
  <table>
    <tr>
      <td><%= f.label :店名 %></td>
      <td><%= f.text_field :name %></td>
    </tr>
    <tr>
      <td><%= f.label :都道府県 %></td>
      <td><%= f.text_field :prefecture %></td>
    </tr>
    <tr>
      <td><%= f.label :city %></td>
      <td><%= f.text_field :city %></td>
    </tr>
    <tr>
      <td><%= f.label :other_address %></td>
      <td><%= f.text_field :other_address %></td>
    </tr>
    <tr>
      <td><%= f.label :tel %></td>
      <td><%= f.text_field :tel %></td>
    </tr>
    <tr>
      <td><%= f.label :business_hour %></td>
      <td><%= f.text_field :business_hour %></td>
    </tr>
    <tr>
      <td><%= f.label :chair %></td>
      <td><%= f.text_field :chair %></td>
    </tr>
    <tr>
      <td><%= f.label :hp %></td>
      <td><%= f.text_field :hp %></td>
    </tr>
    <tr class="radio-edit">
    	<td>Wi-Fi</td>
      <td class="row">
        <label class="col s6"><%= f.radio_button :wifi, true %><span>True</span></label>
        <label class="col s6"><%= f.radio_button :wifi, false %><span>False</span></label>
      </td>
    </tr>
		<tr class="radio-edit">
      <td>socket</td>
      <td class="row">
        <label class="col s6"><%= f.radio_button :socket, true %><span>True</span></label>
        <label class="col s6"><%= f.radio_button :socket, false %><span>False</span></label>
      </td>
    </tr>
    <tr class="radio-edit">
      <td>smoking</td>
      <td class="row">
        <label class="col s6"><%= f.radio_button :smoking, true %><span>True</span></label>
        <label class="col s6"><%= f.radio_button :smoking, false %><span>False</span></label>
      </td>
    </tr>
    <tr class="radio-edit">
      <td>iccard</td>
      <td class="row">
        <label class="col s6"><%= f.radio_button :iccard, true %><span>True</span></label>
        <label class="col s6"><%= f.radio_button :iccard, false %><span>False</span></label>
      </td>
    </tr>
    <tr class="radio-edit">
      <td>is_open</td>
      <td class="row">
        <label class="col s6"><%= f.radio_button :is_open, true %><span>True</span></label>
        <label class="col s6"><%= f.radio_button :is_open, false %><span>False</span></label>
      </td>
    </tr>
    <tr>
      <td><%= f.label :lat %></td>
      <td><%= f.text_field :lat %></td>
    </tr>
    <tr>
      <td><%= f.label :lng %></td>
      <td><%= f.text_field :lng %></td>
    </tr>
    </table>
		<p class="center">
    	<%= f.submit "更新", :class=>"btn" %>
		</p>
<% end %>

app/views/admin/stores/index.html.erb
<h1 class="admin_title">Admin Store</h1>

<ul>
<li><%= link_to 'ログアウト', destroy_user_session_path, method: :delete %></li>
<li><%= link_to 'csv出力', admin_stores_path(format: :csv) %></li>
</ul>
<div id="stores" class="content">
<div id="stores_array">
<div class="stores_box">
<% @stores.each do |store| %>
<div class="store">
	<h2><%= store.name %></h2>
	<div class="row">
		<div class="col s5 mainstore_logo">
			<img src="<%= store.mainstore.image.url %>">
			<p>
				<%= link_to "編集", edit_admin_store_path(store) %>
				<%= link_to "詳細", admin_store_path(store) %>
			</p>
		</div>
		<div class="col s7">
			<table class="table">
				<tbody>
					<tr>
						<th><i class="fas fa-clock"></i></th>
						<td>
							<pre><%= store.business_hour %></pre>
						</td>
					</tr>
					<tr>
						<th><i class="fas fa-map-marker-alt"></i></th>
						<td>
							<%= store.prefecture %><%= store.city %><%= store.other_address %>
						</td>
					</tr>
					<% if store.chair %>
					<tr>
						<th><i class="fas fa-store-alt"></i></th>
						<td class="chair_volume">
							<%= store.chair %>
						</td>
					</tr>
					<% end %>
					<tr>
						<th><i class="fas fa-route"></i></th>
						<td>
							<%= store.access%>
						</td>
					</tr>
					<tr>
						<th><i class="fas fa-location-arrow"></i></th>
						<td>
							約 <%= store.distance %>
						</td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>
<% end %>
<%= paginate @stores %>
</div>
</div>
</div>

app/views/admin/stores/show.html.erb
<h1><%= @store.name %>@Admin</h1>
  <div id="store_detail">
    <div class="container">
    <h2><%= @store.name %></h2>
    <table class="table">
      <tbody>
        <tr>
          <th><i class="fas fa-clock"></i></th>
          <td>
            <pre><%= @store.business_hour %></pre>
          </td>
        </tr>
        <tr>
          <th><i class="fas fa-train"></i></th>
          <td>
            <%= @store.access %>
          </td>
        </tr>
        <tr>
          <th><i class="fas fa-map-marker-alt"></i></th>
          <td>
            <%= @store.prefecture %><%= @store.city %><%= @store.other_address %>
          </td>
        </tr>
        <tr v-show="store.chair">
          <th><i class="fas fa-store-alt"></i></th>
          <td class="chair_volume">
            <%= @store.chair %>
          </td>
        </tr>
        <tr>
          <th><i class="fas fa-phone"></i></th>
          <td>
            <%= @store.tel %>
          </td>
        </tr>
        <tr>
          <th>HP</th>
          <td>
            <a href="<%= @store.hp %>" target="_blank">公式HP</a>
          </td>
        </tr>
      </tbody>
    </table>
    <div class="icons_box">
      <% if @store.smoking %>
      <i class="fas fa-smoking"></i>
      <% end %>
      <% if @store.wifi %>
      <i class="fas fa-wifi"></i>
      <% end %>
      <% if @store.socket %>
      <i class="fas fa-plug"></i>
      <% end %>
      <% if @store.iccard %>
      <div class="iccard_img_block">
        <img src="/uploads/iccard_service.jpg" class="iccard_icon">
      </div>
      <% end %>
    </div>
    <div class="map_block">
      <div id='map'></div>
      <a href="" id="to_map_app" target="_blank">地図アプリで見る</a>
    </div>
    </div>
  </div>

app/views/prefs/show.html.erb
<div class="content" id="stores_index">
  <router-view></router-view>
</div>
<%= javascript_pack_tag 'store' %>

app/views/stores/_store.html.erb
<h2>{{index}}:{{ store.name }}</h2>
      <span>{{ store.access}}</span>
      <div class="row">
        <div class="col s5 mainstore_logo">
          <img v-bind:src="store.mainstore.logo">
        </div>
        <div class="col s7">
          <table class="table">
            <thead>
              <tr>
                <th>営業時間</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  <p>　平日：{{store.weekday_start | moment}}~{{store.weekday_finish | moment }}</p>
                  <p>土曜日：{{store.saturday_start | moment}}~{{store.saturday_finish | moment}}</p>
                  <p>日祝日：{{store.sunday_start | moment}}~{{store.sunday_finish | moment}}</p>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="icons_box">
        <i class="fas fa-smoking" v-show="store.smoking"></i>
        <i class="fas fa-wifi" v-show="store.wifi"></i>
        <i class="fas fa-plug" v-show="store.socket"></i>
      </div>

app/views/stores/_storelist.html.erb
  <div class="store mix"
         v-for="(store,index) in stores"
         :class="{socket: store.socket,wifi: store.wifi}"
        >
        <h2>{{i}}{{ store.name }}</h2>
      <span>{{ store.access}}</span>
      <div class="row">
        <div class="col s5 mainstore_logo">
          <img v-bind:src="store.mainstore.logo">
        </div>
        <div class="col s7">
          <table class="table">
            <thead>
              <tr>
                <th>営業時間</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>
                  <p>　平日：{{store.weekday_start | moment}}~{{store.weekday_finish | moment }}</p>
                  <p>土曜日：{{store.saturday_start | moment}}~{{store.saturday_finish | moment}}</p>
                  <p>日祝日：{{store.sunday_start | moment}}~{{store.sunday_finish | moment}}</p>
                </td>
              </tr>
            </tbody>
          </table>
        </div>
      </div>
      <div class="icons_box">
        <i class="fas fa-smoking" v-show="store.smoking"></i>
        <i class="fas fa-wifi" v-show="store.wifi"></i>
        <i class="fas fa-plug" v-show="store.socket"></i>
      </div>
    </div>
  </div>
  <%= paginate @stores %>

app/views/stores/index.html.erb
<div class="content" id="stores_index">
  <router-view></router-view>
</div>
<%= javascript_pack_tag 'store' %>

app/views/stores/index.js.erb
$("#stores_index").append("<div class='store'><%= escape_javascript(render(@stores)) %></div>");